version: '3'
services:
  postgres:
    build:
      context: .
      dockerfile: ./dockerfile.postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: satoshi
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./src/backend
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/satoshi

  frontend:
    build:
      context: ./src/frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db-data:
